import Navbar from '@/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import { info } from 'autoprefixer'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Projets',
  description: 'Generated by create next app',
}



 
export default function ProjetLayout({ children, informations, projets, contact, commentaires }) {
  return (
    <html className='scroll-smooth' lang="en">
      <body className={inter.className}>
      <div className='scroll-smooth bg-gradient-to-br from-slate-100 via-gray-300 to-zinc-400'>
          <Navbar />
          <div>
            <div id="homepage">
              {children}
            </div>
            <hr className="border-t-2 rounded-xl bg-red-400 border-primary mx-auto w-1/2" />
            <div id="informations" className="bg-slate-100 mt-5 mb-5 pt-5 pb-10 shadow-xl rounded-xl w-11/12 mx-auto">
              <h1 className="text-2xl font-bold pb-5 pr-2 pl-2 ">
                <span className="underline underline-offset-3 " style={{ textDecorationColor: 'hsl(var(--p))' }}>
                  Informations personnelles
                </span>
              </h1>
              {informations}
            </div>
            <hr className="border-t-2 border-primary mx-auto w-1/2" />
            <div id="projets" className="bg-slate-100 mt-5 mb-5 pt-5 pb-10 shadow-xl rounded-xl w-11/12 mx-auto">
              <h1 className="text-2xl font-bold pb-5 pr-2 pl-2">
                <span className="underline underline-offset-3" style={{ textDecorationColor: 'hsl(var(--p))' }}>
                  Mes projets
                </span>
              </h1>
              {projets}
            </div>
            <hr className="border-t-2 border-primary mx-auto w-1/2" />
            <div id="contact" className="bg-slate-100 mt-5 pt-5 pb-5 shadow-xl rounded-xl w-11/12 mx-auto mb-5">
              <h1 className="text-2xl font-bold pb-5 pr-2 pl-2">
                <span className="underline underline-offset-3" style={{ textDecorationColor: 'hsl(var(--p))' }}>
                  Contactez-moi
                </span>
              </h1>

              {contact}
            </div>
            <hr className="border-t-2 border-primary mx-auto w-1/2" />
            <div id="commentaires" className="bg-slate-100 mt-5 pt-5 pb-5 shadow-xl rounded-xl w-11/12 mx-auto mb-5">
              <h1 className="text-2xl font-bold pb-5 pr-2 pl-2">
                <span className="underline underline-offset-3" style={{ textDecorationColor: 'hsl(var(--p))' }}>
                  Commentaires
                </span>
              </h1>

              {commentaires}
            </div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}